# Generated by Django 4.2.3 on 2023-08-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('mailing_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассылки')),
                ('mailing_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Финиш рассылки')),
                ('mailing_period', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='Периодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена'), ('off', 'Отключена модератором')], default='created', max_length=10)),
                ('clients', models.ManyToManyField(to='mail_app.client', verbose_name='Клиенты')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.messagetomailing', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
