# Generated by Django 4.2.3 on 2023-08-27 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_mailingsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglogs',
            options={'ordering': ('attempt_status',), 'verbose_name': 'Лог рассылки', 'verbose_name_plural': 'Логи рассылки'},
        ),
        migrations.AlterModelOptions(
            name='messagetomailing',
            options={'ordering': ('letter_subject',), 'verbose_name': 'Сообщение для рассылки', 'verbose_name_plural': 'Сообщения для рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='datetime_of_last_attempt',
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='mail_server_response',
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_app.mailingsettings', verbose_name='mailing'),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время последней попытки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='mailinglogs',
            name='attempt_status',
            field=models.CharField(choices=[('successful', 'Успешно отправлено'), ('failed', 'Ошибка отправки')], max_length=50, verbose_name='Статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.messagetomailing', verbose_name='Сообщение рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена'), ('off', 'Отключена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='messagetomailing',
            name='letter_body',
            field=models.TextField(verbose_name='тело письма'),
        ),
        migrations.AlterField(
            model_name='messagetomailing',
            name='letter_subject',
            field=models.CharField(max_length=500, verbose_name='тема письма'),
        ),
    ]
