# Generated by Django 4.2.3 on 2023-08-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_client_owner_mailingsettings_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_of_message', to='mail_app.messagetomailing', verbose_name='Сообщение рассылки'),
        ),
    ]
