# Generated by Django 4.2.3 on 2023-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sign_of_publication',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
