# Generated by Django 4.2.3 on 2023-09-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_sign_of_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' человекопонятный URL'),
        ),
    ]
